### PR TITLE
Corrects the formula for finding random number between min and max

### PR DESCRIPTION
**Pull request by anuragagarwal561994**

### CODE REVIEW

**Comment by dobesv** [comment]
I'm not sure if this PR was ignored because it lacks tests, or if the project maintainer just isn't working on this.  But adding tests might not be a bad idea.

**Comment by rawls238** [comment]
Apologies, this fell off my radar. Yes tests for this should be added before it is merged in

**Comment by tdsmith** [comment]
just to add the breadcrumb: would fix #76.

**Comment by rawls238** [comment]
I'll merge this in after a few tests are added for this.

**Comment by rawls238** [comment]
I'm going to go ahead and just merge this in.

**Pull request merged**
