### PR TITLE
NPM: upgrading dependencies

### PR DESCRIPTION
**Pull request by carbonphyber**
- updating all NPM dependencies to newest versions
    - bumping major version due to SemVer rules
    - updating package.json "engines" to reflect new dependencies (Node >= 6.9.0)
    - adding tests to ensure backwards compatibility of exported interface
    - removing use of "add-module-exports" webpack plugin (possible backwards incompatibility for some import techniques)

### CODE REVIEW

**Comment by carbonphyber** [comment]
I chose to discontinue support for NodeJS < `6.9.0` as NodeJS v`8.x` is currently the oldest version currently supported according to [NodeJS Releases](https://nodejs.org/en/about/releases/).
I also removed the babel shim used to deconflict how `default` imports are handled by exporting such that they aren't needed. As this is potentially risky, I added tests to ensure that the fields exported from the dist files match the previous tests.
Hope this PR helps! Thanks for your Open Source contributions!

**Comment by rawls238** [comment]
Awesome, thanks so much for this!

**Comment by rawls238** [comment]
I’ll take this for a spin locally later today

**Comment by rawls238** [comment]
awesome, this is great! Thanks so much for doing this

**Comment by rawls238** [comment]
@jhaber is there any way I could re-gain write access to this repo or have it transferred to my user and maintain it? Doesn't seem as though anyone internally at HubSpot is still looking at this repo?

**Comment by rawls238** [comment]
@gusvargas do you mind merging this in and updating on npm?

**Pull request merged**
